---

- name: Set Prometheus Server system defaults
  template:
    dest: /etc/default/prometheus-server
    mode: 0644
    src: prometheus_server.default.j2

- name: Get list of rule files
  find:
    path: "{{ prometheus2_rule }}"
    patterns: "*.rules"
  register: rules_list

# - name: Create Prometheus Server main config file
#   template:
#     src: prometheus.yml.j2
#     dest: "{{ prometheus2_directory }}/prometheus.yml"
#     validate: "{{ prometheus2_directory }}/promtool check-config %s"

- name: Start Prometheus Server
  service:
    name: prometheus2
    state: started
