---
- hosts: 192.168.122.48
  remote_user: root
  become: yes
  tasks:
    - name: Download Golang 1.9.2
      get_url: {{ golang.tarball_url }}
      dest: /tmp/{{ golang.tarball_url }}
      checksum: sha256:de874549d9a8d8d8062be05808509c09a88a248e77ec14eb77453530829ac02b
      
    - name: Untar Golang 1.9.2
      raw: "tar -xvfz /tmp/{{ golang.tarball }} -C {{ golang.directory }}"

    - name: Set GOPATH and GOROOT
      raw: export something  # TODO: fix export

    - name: Install Prometheus
      include: build.yml
      tags:
        - build

    - name: Configure Prometheus
      include: configure.yml
      tags:
        - configure
